### ISSUE TITLE
does not seem to compile with idf 6.0.0

### ISSUE THREAD

**Issue by savenlid** [david-cermak/libssh#14]
C:/workspace/batteries-chargers/esp32/ch1_p4_6/managed_components/david-cermak__libssh/libssh-0.11.0/include/libssh/libmbedcrypto.h:34:10: fatal error: mbedtls/cipher.h: No such file or directory
   34 | #include <mbedtls/cipher.h>
      |          ^~~~~~~~~~~~~~~~~~

maybe my fault ?

I know things has changed with tls in 6.0
not 100% sure if its related

**Comment by david-cermak** [comment]
Hi, it builds against `v6.0`, just checked the CI job -> https://github.com/david-cermak/libssh/actions/runs/24234558630/job/70753803804?pr=13#step:4:1519
(CI runs against IDF: v5.3, v5.4, v5.5, v6.0, v6.1)

There were mbedtls issues with IDF >= v6.0, but fixed in https://github.com/david-cermak/mbedtls_v3_shim (built a mbedTLS shim as libssh uses v3 API), just make sure you use `mbedtls_v3_shim-v0.1.1`

**Comment by AxelLin** [comment]
Hi @david-cermak 

$ idf.py add-dependency "david-cermak/mbedtls_v3_shim^0.1.1"
$idf.py build
I got below failure:

Compilation failed because crypto.h (in "david-cermak__libssh" component) includes mbedtls/gcm.h, provided by david-cermak__mbedtls_v3_shim component(s).
However, david-cermak__mbedtls_v3_shim component(s) is not in the requirements list of "david-cermak__libssh".
To fix this, add david-cermak__mbedtls_v3_shim to REQUIRES list of idf_component_register call in /home/axel/esp/esp-idf-dev/apps/proj/managed_components/david-cermak__libssh/CMakeLists.txt


BTW, I add david-cermak__mbedtls_v3_shim to REQUIRES list, then I got  error:
```
Compilation failed because agent.c (in "david-cermak__libssh" component) includes config.h, provided by protobuf-c component(s).
However, protobuf-c component(s) is not in the requirements list of "david-cermak__libssh".
```
And then after adding protobuf-c , I got:
```components/david-cermak__libssh/libssh-0.11.0/include/libssh/libssh.h:24:10: fatal error: libssh/libssh_version.h: No such file or directory
   24 | #include <libssh/libssh_version.h>

Missing "libssh/libssh_version.h" file name found in the following component(s): david-cermak__libssh(/home/axel/esp/esp-idf-dev/apps/proj/components/david-cermak__libssh/port/libssh/libssh_version.h). Maybe one of the components needs to add the missing header directory to INCLUDE_DIRS of idf_component_register call in CMakeLists.txt. Another possibility may be that the component or its feature is not enabled in the configuration. Use "idf.py menuconfig" to check if the required options are enabled.

```

**Comment by david-cermak** [comment]
Hi @AxelLin 

Can you share a reproducer?

I believe the private dependency of the shim should be enough, as the mbedtls are included internally.
Are you trying to include sshlib's internal `crypto.h`? That would explain the clash with protobuf-c (since the internal header includes a very generic `config.h` -- and that's okay as long as the include dir is kept private -- but fails if some other component has their own `config.h` as protobuf-c apparently does)

**Comment by AxelLin** [comment]
@david-cermak 

I just try to build again with esp-idf-6.0 branch, but still hit build failures:

1) I hit below failure if CONFIG_LWIP_IPV6=n (This was fixed in upstream libssh v0.11 branch or master)
/home/axel/esp/esp-idf-dev/apps/myproj/components/david-cermak__libssh/libssh-0.11.0/src/match.c:472:24: error: 'INET6_ADDRSTRLEN' undeclared (first use in this function); did you mean 'INET_ADDRSTRLEN'?   
  472 |         if (addr_len > INET6_ADDRSTRLEN + 3) {
      |                        ^~~~~~~~~~~~~~~~
      |                        INET_ADDRSTRLEN


2) Hit below failure, seems "mbedtls/private/ecdh.h" does not exist in esp-idf-6.0.
In file included from /home/axel/esp/esp-idf-dev/apps/myproj/components/david-cermak__libssh/libssh-0.11.0/src/ecdh_mbedcrypto.c:35:
/home/axel/esp/esp-idf-dev/apps/myproj/managed_components/david-cermak__mbedtls_v3_shim/include/mbedtls/ecdh.h:18:10: fatal error: mbedtls/private/ecdh.h: No such file or directory
   18 | #include "mbedtls/private/ecdh.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by AxelLin** [comment]
> Hi, it builds against `v6.0`, just checked the CI job -> https://github.com/david-


Does the CI build for v6.0 tag or v6.0 branch?
I can build with v6.0 tag now, but with current v6.0 branch (v6.0.1-706-ga0688c6e32) I got buil failure:
managed_components/david-cermak__mbedtls_v3_shim/include/mbedtls/ecdh.h:18:10: fatal error: mbedtls/private/ecdh.h: No such file or directory
   18 | #include "mbedtls/private/ecdh.h"


btw, david-cermak/libssh (0.11.0~1)  does not include the commit https://github.com/david-cermak/libssh/commit/08b3763f7a80d5b16fa54a73d041fdd3abd1e57a

**Comment by david-cermak** [comment]
Yes, I can reproduce the issue now, I'll fix it this week.

**Comment by david-cermak** [comment]
[ok](https://github.com/david-cermak/libssh/actions/runs/27019521948/job/81307467109?pr=16), got it working with [mbedtls_v3_shim_v0.1.2](https://components.espressif.com/components/david-cermak/mbedtls_v3_shim/versions/0.1.2), but that's very fragile -- seems like the idea of the mbedtls-shim layer wasn't too smart (it was working/still works with `v6.0` tag, since it can still locate some rom symbols which were removed in recent versions)
I'll check if I can help with adopting mbedtls PSA API in libssh directly

**Comment by AxelLin** [comment]
Tested with v0.12.0~2 on esp-idf-6.0 branch, it's working well.

**Comment by david-cermak** [comment]
Closing as this is resolved from `v0.12.0` (by mbedtls-shim) and from `v0.12.0~2` it uses upstream mbedtls-v4 impl
